/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPaymentsRouteImport } from './routes/_layout/payments'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutPaymentsIndexRouteImport } from './routes/_layout/payments/index'
import { Route as LayoutPaymentsReviewBatchIdRouteImport } from './routes/_layout/payments/review.$batchId'
import { Route as LayoutPaymentsConfirmationBatchIdRouteImport } from './routes/_layout/payments/confirmation.$batchId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentsRoute = LayoutPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentsIndexRoute = LayoutPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPaymentsRoute,
} as any)
const LayoutPaymentsReviewBatchIdRoute =
  LayoutPaymentsReviewBatchIdRouteImport.update({
    id: '/review/$batchId',
    path: '/review/$batchId',
    getParentRoute: () => LayoutPaymentsRoute,
  } as any)
const LayoutPaymentsConfirmationBatchIdRoute =
  LayoutPaymentsConfirmationBatchIdRouteImport.update({
    id: '/confirmation/$batchId',
    path: '/confirmation/$batchId',
    getParentRoute: () => LayoutPaymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/payments': typeof LayoutPaymentsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/payments/': typeof LayoutPaymentsIndexRoute
  '/payments/confirmation/$batchId': typeof LayoutPaymentsConfirmationBatchIdRoute
  '/payments/review/$batchId': typeof LayoutPaymentsReviewBatchIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/payments': typeof LayoutPaymentsIndexRoute
  '/payments/confirmation/$batchId': typeof LayoutPaymentsConfirmationBatchIdRoute
  '/payments/review/$batchId': typeof LayoutPaymentsReviewBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/payments': typeof LayoutPaymentsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/payments/': typeof LayoutPaymentsIndexRoute
  '/_layout/payments/confirmation/$batchId': typeof LayoutPaymentsConfirmationBatchIdRoute
  '/_layout/payments/review/$batchId': typeof LayoutPaymentsReviewBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/payments'
    | '/settings'
    | '/'
    | '/payments/'
    | '/payments/confirmation/$batchId'
    | '/payments/review/$batchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/payments'
    | '/payments/confirmation/$batchId'
    | '/payments/review/$batchId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/payments'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/payments/'
    | '/_layout/payments/confirmation/$batchId'
    | '/_layout/payments/review/$batchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payments': {
      id: '/_layout/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof LayoutPaymentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payments/': {
      id: '/_layout/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof LayoutPaymentsIndexRouteImport
      parentRoute: typeof LayoutPaymentsRoute
    }
    '/_layout/payments/review/$batchId': {
      id: '/_layout/payments/review/$batchId'
      path: '/review/$batchId'
      fullPath: '/payments/review/$batchId'
      preLoaderRoute: typeof LayoutPaymentsReviewBatchIdRouteImport
      parentRoute: typeof LayoutPaymentsRoute
    }
    '/_layout/payments/confirmation/$batchId': {
      id: '/_layout/payments/confirmation/$batchId'
      path: '/confirmation/$batchId'
      fullPath: '/payments/confirmation/$batchId'
      preLoaderRoute: typeof LayoutPaymentsConfirmationBatchIdRouteImport
      parentRoute: typeof LayoutPaymentsRoute
    }
  }
}

interface LayoutPaymentsRouteChildren {
  LayoutPaymentsIndexRoute: typeof LayoutPaymentsIndexRoute
  LayoutPaymentsConfirmationBatchIdRoute: typeof LayoutPaymentsConfirmationBatchIdRoute
  LayoutPaymentsReviewBatchIdRoute: typeof LayoutPaymentsReviewBatchIdRoute
}

const LayoutPaymentsRouteChildren: LayoutPaymentsRouteChildren = {
  LayoutPaymentsIndexRoute: LayoutPaymentsIndexRoute,
  LayoutPaymentsConfirmationBatchIdRoute:
    LayoutPaymentsConfirmationBatchIdRoute,
  LayoutPaymentsReviewBatchIdRoute: LayoutPaymentsReviewBatchIdRoute,
}

const LayoutPaymentsRouteWithChildren = LayoutPaymentsRoute._addFileChildren(
  LayoutPaymentsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPaymentsRoute: typeof LayoutPaymentsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPaymentsRoute: LayoutPaymentsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
